djangoproject/casio/bet/urls.py
from django.urls import path
from . import views

urlpatterns = [
 #   path('', views.initiate_payment, name="initiate-payment"),
    path('addbet/', views.addbet, name="addbet"),
]

djangoproject/casio/casio/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.landingpage,name="home"),
    path("home/",views.home,name="main"),
    path("login/",views.login_view,name="login"),
   # path("fund/",views.fund,name="fund"),
    path("profile/",views.profile,name="profile"),
    path("editprofile/",views.editprofile,name="editprofile"),
    path("draw/",views.draw,name="draw"),
    path("withdraw/",views.withdraw,name="withdraw"),
    path("transaction/",views.transaction,name="transaction"),
    path("notification/",views.notice,name="notice"),
    path("game/",views.game,name="game"),
    path("play/",views.play,name="play"),
    path("changepassword/",views.password,name="password"),
    path("changemail/",views.mail,name="mail"),
    path("settings/",views.setting,name="setting"),
    path("logout/",views.logout_view,name="logout"),
    path("fund/",include('payment.urls')),
    path("bet/",include('bet.urls'))

]

djangoproject/casio/payment/urls.py
from django.urls import path
from . import views
app_name='payment'
urlpatterns = [
 path('', views.process_payment, name="initiate-payment"),
    #path('<str:ref>/', views.verify_payment, name="verify-payment"),
    path('callback', views.payment_response, name='payment_response'),
     path('cryptosuccess', views.cryptosuccess, name='cryptosuccess'),
          path('cryptoerror', views.cryptoerror, name='cryptoerror')
]

djangoproject/casio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'js/tailwind.js' %}"></script>

        <link rel="stylesheet" href="{% static 'css/global.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <title>Home</title>
    <style>
        .active {
            background-color: #27491A80 !important;
        }
    
        .cardbg {
            background: rgba(187, 255, 163, 0.5);
            cursor: pointer;
        }
    
        .p10 {
            font-size: 11px;
        }
    
    </style>
    {% block style %}
    {% endblock %}
<script src="{% static 'js/mobile-sidebar.js' %}"></script>
</head>

<body  class="overflow-x-hidden relative">
    <div id="body"></div>
    <div class="bg-white h-screen flex flex-row w-full">
        <!-- side bar -->
        <div class="hidden md:flex flex-col w-1/5 h-full bg-brand py-5">
            <img src="{% static 'img/casio.svg' %}" class="w-3/4 mx-auto" alt="" srcset="">
            <div class="bg-whi h-full mt-3">
                <a href="{% url 'main' %}">
                    <div class="h-14 hover:bg-green-900 active flex flex-row px-5 items-center text-white">
                        <img src="{% static 'img/home.png' %}" alt="" class="w-5 h-5" srcset="">
                        <p class="px-5">Home</p>
                    </div>
                </a>
                <a href="{% url 'profile' %}">
                    <div class="h-14 hover:bg-green-900 flex flex-row px-5 items-center text-white">
                        <img src="{% static 'img/profile.png' %}" alt="" class="w-4 h-5" srcset="">
                        <p class="px-5">My Profile</p>
                    </div>
                </a>
                <a href="{% url 'payment:initiate-payment' %}">
                    <div class="h-14 hover:bg-green-900 flex flex-row px-5 items-center text-white">
                        <img src="{% static 'img/icons8-wallet-50.png' %}" alt="" class="w-5 h-5" srcset="">
                        <p class="px-5">Fund Wallet</p>
                    </div>
                </a>
                <a href="{% url 'draw' %}">
                    <div class="h-14 hover:bg-green-900 flex flex-row px-5 items-center text-white">
                        <img src="{% static 'img/draw.png' %}" alt="" class="w-5 h-5" srcset="">
                        <p class="px-5">Upcoming Draw</p>
                    </div>
                </a>
                <a href="{% url 'withdraw' %}">
                    <div class="h-14 hover:bg-green-900 flex flex-row px-5 items-center text-white">
                        <i class="fa-sharp fa-solid fa-money-bill-transfer"></i>
                        <p class="px-5">Withdraw Funds</p>
                    </div>
                </a>
                <a href="{% url 'transaction' %}">
                    <div class="h-14 hover:bg-green-900 flex flex-row px-5 items-center text-white">
                        <img src="{% static 'img/files.png' %}" alt="" class="w-5 h-6" srcset="">
                        <p class="px-5">Transactions History</p>
                    </div>
                </a>
                <a href="#">
                    <div class="h-14 hover:bg-green-900 flex flex-row px-5 items-center text-white">
                        <img src="{% static 'img/barge.png' %}" alt="" class="w-5 h-5" srcset="">
                        <p class="px-5">Top Winners</p>
                    </div>
                </a>
                <a href="{% url 'setting' %}">
                    <div class="h-14 hover:bg-green-900 flex flex-row px-5 items-center text-white">
                        <img src="{% static 'img/setting2.png' %}" alt="" class="w-5 h-5" srcset="">
                        <p class="px-5">Settings</p>
                    </div>
                </a>
                <a href="{% url 'logout' %}">
                    <div class="h-14 hover:bg-green-900 flex flex-row px-5 items-center text-white">
                        <img src="{% static 'img/logout.png' %}" alt="" class="w-5 h-5" srcset="">
                        <p class="px-5">Signout</p>
                    </div>
                </a>

                <div class="flex items-center gap-4 mx-4 mt-8">
                    <img src="{% static 'img/user.png' %}" class="w-12 h-12" alt="" srcset="">
                    <div >
                        <h4 class="text-sm text-white">{{userprof.fullname}}</h4>
                        <p class="text-xs text-gray-200">{{request.user.username}}</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- end of side bar -->
        <!-- main -->
        <div class="w-full md:w-4/5 h-full relative">
            <!-- mobile header -->
            <div class="h-14 sticky top-0 left-0 z-30 shadow-md bg-brand w-full px-3 flex md:hidden items-center justify-between">
                <button id="mecnu" onclick="render(document.getElementById(`body`))">
                    <img id="icon" src="{% static 'img/hambergermenu.png' %}" class="w-8 h-8 z-50" alt="" srcset="">
                </button>
            
                <div class="flex items-center gap-4">
                    <img src="{% static 'img/casio.svg' %}" alt="" class="w-40" srcset="">
                    <a href="./notifications.html">
                        <img src="{% static 'img/notification.png' %}" class="w-7 h-7" alt="bell" srcset="">
                    </a>
                </div>
            </div>
            <!-- end mobile header -->
        
    <!-- end of side bar -->
  {% block content %}
  {% endblock %}

     

    
    <!-- end of main  -->
</div>
{% block fundscript %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
</body>
</html>

djangoproject/casio/templates/forgotpassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Forgot Password
</body>
</html>

djangoproject/casio/templates/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'js/tailwind.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <title>Casino</title>
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body class="">
    <div class="flex flex-col md:flex-row w-full h-screen">
        <div class="w-2/6 bg-black hidden md:flex relative bg-[url('{% static "img/dice.jpg" %}')] bg-center bg-no-repeat bg-cover" >
            <div class="absolute top-0 left-0 w-full h-full bg-green-900 opacity-25"></div>
            <img src="{% static 'img/casio.svg' %}" class="z-10 mx-auto w-1/2" alt="logo">
            <p class="cursor-pointer text-sm my-2 text-white z-20 absolute bottom-10 w-full text-center">Have an account already? 
                <a href="{% url 'login' %}" class="px-1 font-semibold text-brand cursor-pointer z-20">Log In</a>
            </p>
        </div>
        <form id="form" class="w-full md:w-4/6 bg-white px-4 md:px-7 py-5">
            <h1 class="font-semibold text-2xl text-brand my-3">Create an account</h1>
            <p class="text-gray-400 text-xs w-4/5 mb-5">Join Casio Lucky Bet today to enjoy the best betting experience</p>
            <label class="text-xs" for="fullname">Full Name</label>
            <div class="bg-white h-10 flex items-center px-3 rounded-md  border mb-3 max-width-400">
                <i class="fa-regular fa-user text-gray-500"></i>
                <input id="fullname" required placeholder="John Doe" class="h-full px-2 text-sm flex-1" >
            </div>
            <!-- email input -->
            <label class="text-xs" for="email">Email Address</label>
            <div class="bg-white h-10 flex items-center px-3 rounded-md  border mb-3 max-width-400">
                <i class="fa-regular fa-envelope text-gray-500"></i>
                <input type="email" id="email" required placeholder="john@gmail.com" class="h-full px-2 text-sm flex-1" >
            </div>
            <!-- Phone Number -->
            <label class="text-xs" for="phone">Phone Number</label>
            <div class="bg-white h-10 flex items-center px-3 rounded-md  border mb-3 max-width-400">
                <i class="fa-regular fa-user text-gray-500"></i>
                <input id="phone" required placeholder="Phone Number" class="h-full px-2 text-sm flex-1">
            </div>
            <!-- password input -->
            <label class="text-xs" for="password">Password</label>
            <div class="bg-white h-10 flex items-center px-3 rounded-md  border mb-3 max-width-400">
                <i class="fa-solid fa-lock text-gray-500"></i>
                <input id="password" type="password" required placeholder="password" class="h-full px-2 text-sm flex-1" >
            </div>
            <label class="text-xs" for="confirmpassword">Confirm Password</label>
            <div class="bg-white h-10 flex items-center px-3 rounded-md  border mb-7 max-width-400">
                <i class="fa-solid fa-lock text-gray-500"></i>
                <input id="confirmpassword" type="password" required placeholder="confirm password" class="h-full px-2 text-sm flex-1" >
            </div>
            <button type="submit" class="bg-brand text-sm h-10 w-full max-width-400 rounded-full text-white">Register with us now</button>
            <p class="text-xs my-2 md:hidden flex">Have an account already? <a href="{% url 'login' %}" class="px-1 font-semibold text-brand">Log In</a></p>
            <!-- OR UI -->
            <!-- <div class="flex items-center justify-center my-3 max-width-400"><hr> <p class="text-gray-500 text-xs">OR</p><hr></div> -->
            <!-- Google Button -->


        </form>
    </div>
    <script>
        document.getElementById("form").addEventListener("submit", (e) => {
            e.preventDefault();

            const password =document.getElementById("password").value;
            const confirmpassword =document.getElementById("confirmpassword").value;
            if (password !== confirmpassword){
                Swal.fire({
                    icon: 'error',
                    title: 'check again...',
                    text: "password does not match"
            })

            }
            else{
                let data = new FormData(); // 2
    
                data.append("email", document.getElementById('email').value)  
                data.append("password", document.getElementById('password').value)
                data.append("phone", document.getElementById('phone').value)
                data.append("fullname", document.getElementById('fullname').value)
                data.append("csrfmiddlewaretoken", '{{csrf_token}}')
                axios.post('/',data)
                
                .then((response) => {
                    console.log(response);
                    if (response.data.status=="Success"){
                        location.href = '/home';
                    }
                    else{
                        Swal.fire({
                            icon: 'error',
                            title: 'oops...',
                            text: response.data.status
                    })
                    }
                  }, (error) => {
                    console.log(error);
                  });

        }
    })
    </script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

</body>
</html>